/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Lofi({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/lofi.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[448.12, -7.74, 0]} rotation={[-Math.PI / 2, 0, 0.46]} scale={[71.58, 100, 100]}>
            <mesh geometry={nodes.Cube005_Material004_0.geometry} material={materials['Material.004']} />
            <mesh geometry={nodes.Cube005_books_0.geometry} material={materials.books} />
            <mesh geometry={nodes.Cube005_pot_0.geometry} material={materials.material} />
            <mesh geometry={nodes.Cube005_hairband_0.geometry} material={materials.hairband} />
            <mesh geometry={nodes.Cube005_trtleneck_0.geometry} material={materials.trtleneck} />
            <mesh geometry={nodes.Cube005_table_0.geometry} material={materials.material_0} />
            <mesh geometry={nodes.Cube005_Material002_0.geometry} material={materials['Material.002']} />
            <mesh geometry={nodes.Cube005_wewd_0.geometry} material={materials.wewd} />
            <mesh geometry={nodes.Cube005_groots_0.geometry} material={materials.groots} />
            <mesh geometry={nodes.Cube005_clothes_0.geometry} material={materials.clothes} />
            <mesh geometry={nodes.Cube005_hingez_0.geometry} material={materials.hingez} />
            <mesh geometry={nodes.Cube005_epic_cup_0.geometry} material={materials.epic_cup} />
            <mesh geometry={nodes.Cube005_Material003_0.geometry} material={materials['Material.003']} />
            <mesh geometry={nodes.Cube005_laptop_below_0.geometry} material={materials.laptop_below} />
            <mesh geometry={nodes.Cube005_h_0.geometry} material={materials.material_14} />
            <mesh geometry={nodes.Cube005_headcup_0.geometry} material={materials.headcup} />
            <mesh geometry={nodes.Cube005_lamp_color_0.geometry} material={materials.lamp_color} />
            <mesh geometry={nodes.Cube005_laptop_casing_0.geometry} material={materials.laptop_casing} />
            <mesh geometry={nodes.Cube005_window_0.geometry} material={materials.window} />
            <mesh geometry={nodes.Cube005_white_lmao_0.geometry} material={materials.white_lmao} />
            <mesh geometry={nodes.Cube005_wall_0.geometry} material={materials.wall} />
            <mesh geometry={nodes.Cube005_window_supp_0.geometry} material={materials.window_supp} />
            <mesh geometry={nodes.Cube005_clanender_0.geometry} material={materials.clanender} />
            <mesh geometry={nodes.Cube005_hand_and_stuff_0.geometry} material={materials.hand_and_stuff} />
            <mesh geometry={nodes.Cube005_skin_0.geometry} material={materials.skin} />
            <mesh geometry={nodes.Cube005_radeo_0.geometry} material={materials.radeo} />
            <mesh geometry={nodes.Cube005_hair_0.geometry} material={materials.hair} />
            <mesh geometry={nodes.Cube005_rocks001_0.geometry} material={materials['rocks.001']} />
            <mesh geometry={nodes.Cube005_Material001_0.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Cube005_rest_ct_0.geometry} material={materials.rest_ct} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/lofi.glb')
